mod abstractions;
mod architecture;
mod chunker;
mod commands;
mod detect;
mod diff;
mod exports;
mod hash;
mod markdown;
mod metadata;
mod onboarding;
mod pipeline;
mod sliding;

pub use abstractions::extract_key_abstractions;
pub use architecture::analyze_directory_structure;
pub use chunker::{Language, RawChunk, TreeSitterChunker};
pub use commands::extract_build_commands;
pub use detect::{detect_language, ChunkerKind};
pub use diff::{detect_changed_files, ChangedFiles};
pub use exports::{read_exports_jsonl, write_exports_jsonl, TreeSitterExportExtractor};
pub use hash::{content_hash, has_chunk_changed};
pub use markdown::MarkdownChunker;
pub use metadata::detect_project_metadata;
pub use onboarding::run_onboarding;
pub use pipeline::{IngestPipeline, IngestReport};
pub use sliding::SlidingWindowChunker;
